const getters = {
  sidebar: state => state.app.sidebar,
  device: state => state.app.device,
  adminToken: state => state.adminUser.adminToken,
  adminAvatar: state => state.adminUser.adminAvatar,
  adminUserId: state => state.adminUser.adminUserId,
  adminName: state => state.adminUser.adminName,
  adminRoles: state => state.adminUser.adminRoles,
  adminPerms: state => state.adminUser.adminPerms,
  adminLastLoginIp: state => state.adminUser.adminLastLoginIp,
  adminLastLoginTime: state => state.adminUser.adminLastLoginTime,
  adminPerms: state => state.adminUser.adminPerms,
  addRoutes: state => state.permission.addRoutes,
  routes: state => state.permission.routes,
  editableTabs: state => state.tag.editableTabs,
  collapse: state => state.tag.collapse,
  userDetailName: state => state.statisticsDetail.userDetailName,
  userRadio:state => state.statisticsDetail.userRadio,
  userDateState: state => state.statisticsDetail.userDateState,
  userSpecifiedTime1: state => state.statisticsDetail.userSpecifiedTime1,
  userSpecifiedTime2: state => state.statisticsDetail.userSpecifiedTime2,
  consumableDateState: state => state.statisticsDetail.consumableDateState,
  consumableRadio:state => state.statisticsDetail.consumableRadio,
  consumableTitle: state => state.statisticsDetail.consumableTitle,
  consumableSkusTitle: state => state.statisticsDetail.consumableSkusTitle,
  consumableSpecifiedTime1: state => state.statisticsDetail.consumableSpecifiedTime1,
  consumableSpecifiedTime2: state => state.statisticsDetail.consumableSpecifiedTime2,
  orderSn:state=>state.order.orderSn

}
export default getters
